In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio
pio.templates.default = "plotly"

In [32]:
# ! pip install SQLAlchemy
# ! pip install pymysql

### Data Loading

In [33]:
# from sqlalchemy import create_engine

# connection = create_engine("mysql+pymysql://root:2416734@localhost:3306/ecommdb")

# chunks = pd.read_sql(sql= 'SELECT * FROM customers;',
#             con= connection,
#             chunksize= 100)

# pd.concat(chunks, axis= 0)

In [34]:
from sqlalchemy import create_engine

connection = create_engine("mysql+pymysql://root:2416734@localhost:3306/ecommdb")

customers = pd.read_sql(sql= 'SELECT * FROM customers;',con= connection)
orders = pd.read_sql(sql= 'SELECT * FROM orders;',con= connection)
products = pd.read_sql(sql= 'SELECT * FROM products;',con= connection)
sales = pd.read_sql(sql= 'SELECT * FROM sales;',con= connection)

In [35]:
orders

     order_id  customer_id  order_date delivery_date
0           1           64  30/08/2021    24/09/2021
1           2          473  03/02/2021    13/02/2021
2           3          774  08/10/2021    03/11/2021
3           4          433  06/05/2021    19/05/2021
4           5          441  23/03/2021    24/03/2021
..        ...          ...         ...           ...
995       996          345  13/01/2021    02/02/2021
996       997          346  18/01/2021    31/01/2021
997       998          407  05/05/2021    21/05/2021
998       999          428  15/06/2021    12/07/2021
999      1000          896  07/04/2021    24/04/2021

[1000 rows x 4 columns]

In [36]:
df = pd.merge(left= customers, right= orders, how='inner', on= 'customer_id')
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,729,18/02/2021,01/03/2021
3,7,Winslow Ewbanck,Bigender,76,92 Hills Station StApt. 683,793,Masonfurt,Queensland,Australia,465,21/05/2021,23/05/2021
4,10,Susanetta Wilshin,Bigender,70,615 Hayley KnollSuite 454,2118,Joelburgh,Western Australia,Australia,595,09/03/2021,29/03/2021

In [37]:
df = pd.merge(left= df, right= sales, how='inner', on= 'order_id')
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2245,211,106,3,318
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2246,783,91,2,182
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3324,525,98,2,196
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3325,792,91,2,182
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3326,179,98,1,98

In [38]:
df = pd.merge(left= df, right= products, how='inner', left_on= 'product_id', right_on = 'product_ID')
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity_x,total_price,product_ID,product_type,product_name,size,colour,quantity_y,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2245,211,106,3,318,211,Shirt,Chambray,S,red,72,"A red coloured, S sized, Chambray Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2246,783,91,2,182,783,Jacket,Pullover,L,yellow,43,"A yellow coloured, L sized, Pullover Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3324,525,98,2,196,525,Jacket,Leather,XS,red,67,"A red coloured, XS sized, Leather Jacket"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3325,792,91,2,182,792,Jacket,Pullover,M,blue,44,"A blue coloured, M sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3326,179,98,1,98,179,Shirt,Camp Collared,XL,red,79,"A red coloured, XL sized, Camp Collared Shirt"

In [39]:
df.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'home_address',
       'zip_code', 'city', 'state', 'country', 'order_id', 'order_date',
       'delivery_date', 'sales_id', 'product_id', 'price_per_unit',
       'quantity_x', 'total_price', 'product_ID', 'product_type',
       'product_name', 'size', 'colour', 'quantity_y', 'description'],
      dtype='object')

In [40]:
df = df.rename(columns= {'quantity_x' : 'quantity', 'quantity_y' : 'Stock'})
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price,product_ID,product_type,product_name,size,colour,Stock,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2245,211,106,3,318,211,Shirt,Chambray,S,red,72,"A red coloured, S sized, Chambray Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2246,783,91,2,182,783,Jacket,Pullover,L,yellow,43,"A yellow coloured, L sized, Pullover Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3324,525,98,2,196,525,Jacket,Leather,XS,red,67,"A red coloured, XS sized, Leather Jacket"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3325,792,91,2,182,792,Jacket,Pullover,M,blue,44,"A blue coloured, M sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3326,179,98,1,98,179,Shirt,Camp Collared,XL,red,79,"A red coloured, XL sized, Camp Collared Shirt"

In [41]:
# To show all columns

pd.set_option('display.max_columns', None)

In [42]:
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price,product_ID,product_type,product_name,size,colour,Stock,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2245,211,106,3,318,211,Shirt,Chambray,S,red,72,"A red coloured, S sized, Chambray Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,04/04/2021,06/04/2021,2246,783,91,2,182,783,Jacket,Pullover,L,yellow,43,"A yellow coloured, L sized, Pullover Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3324,525,98,2,196,525,Jacket,Leather,XS,red,67,"A red coloured, XS sized, Leather Jacket"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3325,792,91,2,182,792,Jacket,Pullover,M,blue,44,"A blue coloured, M sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,06/03/2021,01/04/2021,3326,179,98,1,98,179,Shirt,Camp Collared,XL,red,79,"A red coloured, XL sized, Camp Collared Shirt"

## Data Exploration

In [43]:
# Check Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     5000 non-null   int64
 1   customer_name   5000 non-null   object
 2   gender          5000 non-null   object
 3   age             5000 non-null   int64
 4   home_address    5000 non-null   object
 5   zip_code        5000 non-null   int64
 6   city            5000 non-null   object
 7   state           5000 non-null   object
 8   country         5000 non-null   object
 9   order_id        5000 non-null   int64
 10  order_date      5000 non-null   object
 11  delivery_date   5000 non-null   object
 12  sales_id        5000 non-null   int64
 13  product_id      5000 non-null   int64
 14  price_per_unit  5000 non-null   int64
 15  quantity        5000 non-null   int64
 16  total_price     5000 non-null   int64
 17  product_ID      5000 non-null   int64
 18  product_type    5000 non-null   object
 19  product_name    5000 non-null   object
 20  size            5000 non-null   object
 21  colour          5000 non-null   object
 22  Stock           5000 non-null   int64
 23  description     5000 non-null   object
dtypes: int64(11), object(13)
memory usage: 937.6+ KB

In [44]:
# Check Duplicates
df.duplicated().sum()

0

In [45]:
# Check summary statistics for Numerical Columns
df.describe().round(2)

,customer_id,age,zip_code,order_id,sales_id,product_id,price_per_unit,quantity,total_price,product_ID,Stock
count,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.0,5000.00,5000.00,5000.00,5000.00
mean,504.56,48.76,4912.36,503.04,2499.50,634.05,103.5,1.99,206.36,634.05,60.08
std,276.50,17.58,2907.37,285.96,1443.52,363.26,9.2,0.81,86.36,363.26,11.68
min,1.00,20.00,52.00,1.00,0.00,1.00,90.0,1.00,90.00,1.00,40.00
25%,276.00,34.00,2273.00,258.00,1249.75,323.00,95.0,1.00,112.00,323.00,50.00
50%,509.00,48.00,4750.00,504.50,2499.50,635.00,102.0,2.00,204.00,635.00,60.00
75%,733.00,63.00,7460.25,749.00,3749.25,951.00,112.0,3.00,285.00,951.00,70.00
max,1000.00,80.00,9998.00,999.00,4999.00,1259.00,119.0,3.00,357.00,1259.00,80.00

In [46]:
# Check summary statistics for Categorical Columns
df.describe(include= 'object')

,customer_name,gender,home_address,city,state,country,order_date,delivery_date,product_type,product_name,size,colour,description
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,616,8,616,604,8,1,291,304,3,35,5,7,1233
top,Kristofor Roos,Female,5567 Clarke MallApt. 756,Jordanside,South Australia,Australia,21/06/2021,28/03/2021,Trousers,Denim,M,blue,"A orange coloured, L sized, Flannel Shirt"
freq,37,712,37,37,718,5000,51,49,1683,273,1022,762,13

In [47]:
# Check Missing Values
df.isna().sum()

customer_id       0
customer_name     0
gender            0
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
order_id          0
order_date        0
delivery_date     0
sales_id          0
product_id        0
price_per_unit    0
quantity          0
total_price       0
product_ID        0
product_type      0
product_name      0
size              0
colour            0
Stock             0
description       0
dtype: int64

## Data Cleaning

In [48]:
# Drop Unnecessary Columns

df.drop(['customer_id', 'home_address', 'zip_code', 'country', 'order_id', 'product_id', 'product_ID', 'description'], axis= 1, inplace= True)

In [49]:
# Check duplicates
df.duplicated().sum()

0

In [50]:
df.head(1)

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock
0,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,04/04/2021,06/04/2021,2245,106,3,318,Shirt,Chambray,S,red,72

In [51]:
# Convert to datetime

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst= True)
df['delivery_date'] = pd.to_datetime(df['delivery_date'], dayfirst= True)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_name   5000 non-null   object
 1   gender          5000 non-null   object
 2   age             5000 non-null   int64
 3   city            5000 non-null   object
 4   state           5000 non-null   object
 5   order_date      5000 non-null   datetime64[ns]
 6   delivery_date   5000 non-null   datetime64[ns]
 7   sales_id        5000 non-null   int64
 8   price_per_unit  5000 non-null   int64
 9   quantity        5000 non-null   int64
 10  total_price     5000 non-null   int64
 11  product_type    5000 non-null   object
 12  product_name    5000 non-null   object
 13  size            5000 non-null   object
 14  colour          5000 non-null   object
 15  Stock           5000 non-null   int64
dtypes: datetime64[ns](2), int64(6), object(8)
memory usage: 625.1+ KB

- In depth check for numerical columns

In [53]:
num_cols = df.select_dtypes(include= 'number').columns.drop('sales_id')
num_cols

Index(['age', 'price_per_unit', 'quantity', 'total_price', 'Stock'], dtype='object')

In [54]:
for col in num_cols:

    px.histogram(data_frame= df, x= col, title= col).show()

- In depth check for categorical columns

In [55]:
cat_cols = df.select_dtypes(include= 'object').columns.drop('customer_name')
cat_cols

Index(['gender', 'city', 'state', 'product_type', 'product_name', 'size',
       'colour'],
      dtype='object')

In [56]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

gender
8
['Female' 'Bigender' 'Agender' 'Male' 'Genderfluid' 'Genderqueer'
 'Non-binary' 'Polygender']
----------------------------------------------------------------------------------------------------
city
604
['Johnstonhaven' 'Masonfurt' 'Joelburgh' 'Georgeland' 'Taylorburgh'
 'Maddisonmouth' 'Kiehnburgh' 'New Kai' 'Walterland' 'West Bailey'
 'East Audrey' 'South Callum' 'Maxberg' 'North Mia' 'Olivershire'
 'New Oliverside' 'Lake Alanafort' 'West Noah' 'Sauerfort' 'Port Lucas'
 'Port Claudia' 'Port Ella' 'Gabriellatown' 'Eliburgh' 'Leofurt'
 'Bartolettiside' 'Lake Nicholasfurt' 'Port Alyssa' 'East Aidan'
 'South Evaport' 'Chelseahaven' 'West Alyssa' 'Lake Phoenixside'
 'Amelieburgh' 'New Callum' 'Samuelland' 'New Beaumouth' 'Sanfordborough'
 'West Justin' 'East Sofia' 'Codyview' 'Braunhaven' 'Monahanside'
 'Smythland' 'Hellermouth' 'Chloeville' 'Lake Alihaven' 'Sofiaberg'
 'Spencerborough' 'Walshland' 'Lake Paigemouth' 'East Chelsea'
 'Gleasonport' 'Savannahland' 'Port Liam' 'Lake Hannah' 'Harrismouth'
 'Colestad' 'East Isla' 'Port Jordan' 'Hudsontown' 'North Ellabury'
 'Port Madelineberg' 'Lake Callumville' 'Port Sarah' 'South Nathan'
 'Joelland' 'Stokestown' 'Claudiaview' 'Port Rosemouth' 'Bartolettifurt'
 'North Edwardshire' 'West Hamish' 'North Ruby' 'Zacharyborough'
 'New Ellieland' 'South Cameron' 'Carterbury' 'Jordanborough'
 'Donnellyfort' 'Angelinaville' 'South Adam' 'Jacobsland'
 'Port Harrychester' 'Shieldsside' 'South Hannah' 'Port Abigail'
 'Hudsonberg' 'Chelseaview' 'Richardshaven' 'North Kayla'
 'North Scarlettborough' 'Harryburgh' 'Port Sophia' 'Kaiberg'
 'Johnschester' 'Hicklebury' 'Port Jade' 'Port Elliechester' 'Ellieshire'
 'South Georgia' 'South Gabriel' 'Lake Johnchester' 'Lewiston'
 'Callumborough' 'Chasemouth' 'Port Joshuaside' 'New Angelina'
 'Violetborough' 'West Isabelton' 'Lake Abigailhaven' 'Grimesstad'
 'East Mason' 'West Baileyville' 'New Ava' 'Gardenchester'
 'Lake Declanland' 'Joelmouth' 'Lake Elijah' 'East Jakeberg'
 'South Clairetown' 'Elijahburgh' 'Josephland' 'Bayermouth' 'Codyfort'
 'Port Logan' 'Justinport' 'Lake Lucas' 'Connellyport' 'East Gabriel'
 'Lake Owen' 'Hansenberg' 'Muellerfurt' 'South Holly' 'Towneport'
 'Wildermanside' 'Lake Matilda' 'Casperfurt' 'West Zoe' 'East Sienna'
 'Lake Mollyburgh' 'New Sophie' 'North Sophie' 'New Codyville'
 'Port Chelseaport' 'West Kiara' 'Mayerland' 'Boyleberg' 'Wilsonside'
 'Beiermouth' 'North Lillian' 'Johnstonshire' 'South Declan' 'Trompview'
 'West Cameron' 'Port Michael' 'Lake Laurenview' 'Laylabury' 'Lukefurt'
 'West Michael' 'New Jadehaven' 'New Angelinaberg' 'Noahmouth'
 'Gardenport' 'North Josephmouth' 'Port Hannahburgh' 'New George'
 'Charlotteville' 'Reillyfurt' 'East Kaylabury' 'West Siennaland'
 'West Aidenview' 'Sanfordberg' 'Lake Amelia' 'Hermistonside' 'New Sienna'
 'North Paige' 'Lake Aidan' 'West Audreyhaven' 'West Madison'
 'Lake Edward' 'Fadelburgh' 'Fayburgh' 'South Pipermouth'
 'East Michaelmouth' 'Christopherside' 'Miafort' 'Georgiatown' 'Howehaven'
 'Kaihaven' 'South Jayden' 'West Claudia' 'New Masonport'
 'Port Marcusshire' 'North Elijahshire' 'South Claudialand' 'Lincolnbury'
 'Aidenton' 'East George' 'West Marcus' 'New Alyssa' 'Port Madison'
 'Cooperbury' 'Monahanberg' 'Jasmineville' 'Barrowschester' 'Lake Charli'
 'Audreyfurt' 'Olsonbury' 'Levihaven' 'Rubyfort' 'North Alex'
 'Port Ashtonhaven' 'North Kaylastad' 'Kreigerbury' 'East Lauren'
 'Kingmouth' 'West Zoeberg' 'Swiftfort' 'Jacobsshire' 'Youngview'
 'Jasperside' 'South Chelseaton' 'New Stellastad' 'Abbottbury'
 'West Jessica' 'East Sophia' 'Ernserland' 'Rodriguezbury'
 'South Hannahstad' 'Matthewstad' 'New Mayaburgh' 'Lake Lukeberg'
 'South Eveshire' 'North Sophieland' 'Audreyport' 'Isabellaton'
 'Gabrielville' 'South Logan' 'Sarahstad' 'West Cooper' 'West Ellaport'
 'Hartmannshire' 'Lake Haydenton' 'New Chase' 'Hackettchester'
 'Morissetteborough' 'North Ivy' 'Dietrichville' 'Langworthville'
 'Fadelland' 'North Sebastianberg' 'West Mackenzie' 'North Baileyside'
 'Feeneymouth' 'New Rileybury' 'South Sophieview' 'North Liamfort'
 'Jademouth' 'North Cody' 'West Michaelport' 'West Amber' 'South Tobyton'
 'Port Siennaport' 'West Thomas' 'South Rileyview' 'Port Chloe'
 'Crooksshire' 'Macdonaldchester' 'North Lukeshire' 'Zacshire' 'Liamton'
 'West Lucy' 'Scottview' 'Kreigerberg' 'Port Isabellafurt' 'Lake Sienna'
 'West Lachlan' 'Charlotteborough' 'Mayaview' 'Ellashire'
 'West Chasemouth' "D'amoreborough" 'Lake Mikaylashire' 'Williammouth'
 'North Justin' "O'reillychester" 'West Isla' 'Andrewborough' 'Edwardtown'
 'Boyerland' 'Parisianmouth' 'Annaton' 'New Matildaville' 'West Jackfort'
 'Lake Lillyville' 'Mullerberg' 'East Joshua' 'Port Lily' 'Port Lillian'
 'West Phoenix' 'Mollyland' 'Josephmouth' 'Port Natalie' 'Evansburgh'
 'North Aidentown' 'New Hannah' 'Port Haydenchester' 'Kiehnchester'
 'Emilymouth' 'South Hugoberg' 'Jaydenside' 'West Annaport'
 'Alexandramouth' 'Port Ali' 'Huelhaven' 'South Tylermouth' 'Bauchton'
 'Handborough' 'North Jasperville' 'Port Sebastianland' 'Adamsside'
 'Lake Madelineton' 'Lake Rose' 'Andersonburgh' 'Conroychester' 'Krisland'
 'Port Blake' 'Durgantown' 'West Elliestad' 'Gleasonburgh' 'Sophiafurt'
 'Declanton' 'Kaiview' 'New Benjaminborough' 'Lake Jacobborough'
 'West Kai' 'Lake Jesse' 'Violetfort' 'West Rubyland' 'North Marcusland'
 'Hamiltonport' "O'keefeton" 'East Piper' 'New Masonstad' 'Jordanside'
 'Sanfordton' 'Abbeyshire' 'Zacharybury' 'Heaneyview' 'East Marcus'
 'Hackettland' 'Leomouth' 'West Bella' 'Hallhaven' 'East Declanside'
 'West Danieltown' 'Hoppetown' 'North Stephanie' 'Ameliaview'
 'Lake Michaelbury' 'Sebastianbury' 'East Imogen' 'Hamiltonshire'
 'Calebville' 'North Gracetown' 'New Emilyton' 'New Jayden'
 'West Hayleyhaven' 'Angelinastad' 'Samuelside' 'Willowmouth' 'Jettstad'
 'West Ashley' 'Lake Phoebe' 'Walterstad' 'Port Christopher' 'West Sophie'
 'Amberland' 'New Madisonborough' 'Davidfurt' 'South Anthonyburgh'
 'East Mackenzietown' 'Abbottburgh' 'Lilystad' 'Reillyborough'
 'Lake Alice' 'Lincolnchester' 'Hamishview' 'Shieldschester' 'Baileyberg'
 'Lake Nicholasfort' 'New Emmastad' 'Schneiderbury' 'Evastad'
 'North Isabelleside' 'Lachlanstad' 'West Sebastianfort' 'Mitchellhaven'
 'Port Eveland' 'Sophiemouth' 'Charlesshire' 'North Beau' 'Pipershire'
 'East Max' 'Kiehnstad' 'New Beau' 'Bauchland' 'Goodwinmouth' 'Kaylafurt'
 'North Mikayla' 'East Alex' 'Cameronton' 'Taylorfurt' 'West Alyssaton'
 'Sofiahaven' 'West Finnberg' 'Laurenview' 'Dickensshire' 'East Ruby'
 'Port Annabelle' 'Abigailshire' 'Laraview' 'Beattychester' 'Callummouth'
 'Port Cody' 'New Isaac' 'Port Joeltown' 'Lake Aiden' 'West Olivertown'
 'East Lillyville' 'Kulasville' 'Russelstad' 'West Addison' 'Port Hunter'
 'Haydenhaven' 'Lake Mitchellbury' 'Hoppeville' 'Gracemouth' 'Cassinport'
 'Jacobport' 'Lake Matildaville' 'Cameronport' 'North Jessica'
 'Port Aaronton' 'East Benjamin' 'Port Alanamouth' 'Doylebury'
 'Harveyside' 'Hollyfort' 'East Matthewville' 'Port Molly' 'Port Aliview'
 'North Matthewfort' 'Lake Gabriella' 'Baumbachton' 'West Aaron'
 'East Xavier' 'East Madison' 'West Aidanton' 'South Codyhaven'
 'Hettingerfort' 'Eveside' 'Port Isabel' 'West Grace' 'Port Isabelle'
 'Kuhntown' 'Oscarberg' 'Thomasborough' 'West Jonathanshire'
 'East Charlesfurt' 'Harveyville' 'Blakemouth' 'Caitlinview' 'Madisonland'
 'North Avabury' 'Port Adamburgh' 'Graceville' 'Davidshire' 'Phoebeberg'
 'Aliceland' 'Nathanfort' 'Elijahshire' 'Port Anna' 'East Hayden'
 'New Leah' 'Marcusshire' 'South Levi' 'Daughertyport' 'Blakeborough'
 'Imogenmouth' 'Amyton' 'Tylershire' 'Robertstown' 'South Tyler'
 'South Maxland' 'Lucyport' 'Tillmanview' 'Kaifort' 'Johnsonstad'
 'West Eviebury' 'Alexanderland' 'Haleybury' 'Thomaschester'
 'Lake Alicefurt' 'East Zacharystad' 'Baumbachtown' 'New Ruby'
 'Jaspermouth' 'Port Ellaside' 'North Lachlanfurt' 'Ryanberg' 'Islamouth'
 'Kulasmouth' 'Port Kiara' 'Lake Addisonland' 'Alexandraville' 'Davidtown'
 'Zacville' 'Lake Gabrielview' 'North Emmashire' "O'connertown"
 'Siennabury' 'Walkertown' 'West Joelmouth' 'North Riley'
 'Port Davidburgh' 'New Charlieville' 'New Jackson' 'Lake Ashleyhaven'
 'Port Joshualand' 'West Lukeshire' 'Samanthatown' 'South Zacmouth'
 'New Aidenfurt' 'Lake William' 'Kiehnfurt' 'Beahantown' 'Macdonaldtown'
 'Thompsonport' 'South Emilyborough' 'Beahanport' 'West Annaton'
 'Port Jettshire' 'Lake Bellahaven' 'Angelinaport' 'East Emily'
 'West Dylanport' 'Ebertfurt' 'North Caitlin' 'South Alexandraview'
 'Langfort' 'West John' 'South Alexview' 'West Benjaminberg' 'Violetstad'
 'Rutherfordville' 'Port Zoeborough' 'Jordanburgh' 'South Ellieburgh'
 'Andersonchester' 'East Jasper' 'Ryanfurt' 'Haydentown' 'Beahanfurt'
 'Port Lillianside' 'Lake Oliverberg' 'Huelfort' 'Schneiderstad'
 'Harberview' 'Farrellchester' 'North Nicholaston' 'Stantonmouth'
 'South Jasper' 'South Charles' 'Bergefort' 'New Mollystad' 'Michaelfurt'
 'Lake Evemouth' 'Lake Owenfurt' 'New Alexchester' 'Samanthaberg'
 'West Luke' 'New Callumtown' 'South Heidi' 'West Stella' 'Lake Lincoln'
 'East Chasehaven' 'West Callumside' 'South Xavierport' 'Isaacberg'
 'Hannahberg' 'North Mackenzieborough' 'Turcottetown' 'Thompsonbury'
 'New Harry' 'Stewartland' 'North Andrew' 'Michaelberg' 'Hallshire'
 'Hermistonberg' 'Lake Danielland' 'Kohlerberg' 'Lake Audreyborough']
----------------------------------------------------------------------------------------------------
state
8
['Northern Territory' 'Queensland' 'Western Australia' 'South Australia'
 'Victoria' 'New South Wales' 'Tasmania' 'Australian Capital Territory']
----------------------------------------------------------------------------------------------------
product_type
3
['Shirt' 'Jacket' 'Trousers']
----------------------------------------------------------------------------------------------------
product_name
35
['Chambray' 'Pullover' 'Leather' 'Camp Collared' 'Cropped'
 'Tracksuit Bottoms' 'Shearling' 'Casual Slim Fit' 'Wool' 'Relaxed Leg'
 'Linen' 'Bomber' 'Windbreaker' 'Chinos' 'Coach' 'Pleated' 'Puffer'
 'Cardigan' 'Peacoat' 'High-Waisted' 'Slim-Fit' 'Denim' 'Oxford Cloth'
 'Drawstring' 'Flannel' 'Joggers' 'Cuban Collar' 'Mandarin Collar'
 'Trench Coat' 'Cargo Pants' 'Dress' 'Cords' 'Parka' 'Polo' 'Henley']
----------------------------------------------------------------------------------------------------
size
5
['S' 'L' 'XS' 'M' 'XL']
----------------------------------------------------------------------------------------------------
colour
7
['red' 'yellow' 'blue' 'green' 'violet' 'orange' 'indigo']
----------------------------------------------------------------------------------------------------

## Feature Engineering

In [57]:
df.head()

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock
0,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,2021-04-04,2021-04-06,2245,106,3,318,Shirt,Chambray,S,red,72
1,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,2021-04-04,2021-04-06,2246,91,2,182,Jacket,Pullover,L,yellow,43
2,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,2021-03-06,2021-04-01,3324,98,2,196,Jacket,Leather,XS,red,67
3,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,2021-03-06,2021-04-01,3325,91,2,182,Jacket,Pullover,M,blue,44
4,Leanna Busson,Female,30,Johnstonhaven,Northern Territory,2021-03-06,2021-04-01,3326,98,1,98,Shirt,Camp Collared,XL,red,79

In [58]:
df['delivery_days'] = (df['delivery_date'] - df['order_date']).dt.days
df['delivery_days']

0        2
1        2
2       26
3       26
4       26
        ..
4995     2
4996     2
4997     2
4998     2
4999     2
Name: delivery_days, Length: 5000, dtype: int64

In [59]:
df['order_date'].describe()

count                          5000
mean     2021-05-25 15:10:39.360000
min             2021-01-01 00:00:00
25%             2021-03-13 00:00:00
50%             2021-05-24 00:00:00
75%             2021-08-08 00:00:00
max             2021-10-24 00:00:00
Name: order_date, dtype: object

# Deployment

In [31]:
df.to_csv('cleaned_df.csv', index= False)

In [32]:
# Only run once
! streamlit run Home.py

^C

In [ ]:
import pipreqs

! pipreqs ./

WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.0.2" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in ./requirements.txt